substitutions:
  name: living
  friendly_name: living
  remote_temp_sensor: living_temperature

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp8266:
  board: esp12e

logger:
  baud_rate: 0  #disable hardware UART log to use pins for UART communication with the AC unit
  level: DEBUG

external_components:
  - source: github://makusets/esphome-toshiba-ab
    refresh: 0s

uart:
  tx_pin: GPIO15
  rx_pin: GPIO13
  baud_rate: 2400
  parity: EVEN
  rx_buffer_size: 2048

# Home Assistant
api:
  encryption:
    key: !secret api_key

# Enable Web server
#web_server:
#  port: 80

climate:
  - platform: toshiba_ab
    name: AC
    id: ac
    connected:
      name: "Toshiba AC Connected"
    master: 0x04 # Master ID in Toshiba protocol, optional, default is 0x00, for some units needs to be set to 0x01
    report_sensor_temp:
      enabled: true
      sensor: ${remote_temp_sensor} # must match an existing temp sensor id in this yaml file
      interval: 1min                # default 5min if omitted

sensor:
  # Remote Temperature Sensor
  - platform: homeassistant
    name: "Remote Temperature Sensor"
    id: ${remote_temp_sensor} # must match the id used in the climate section above if used to report temp to AC
    entity_id: sensor.${remote_temp_sensor} # Replace with your HomeAssistant remote sensor entity id, or include in substitutions
    internal: false
    disabled_by_default: true
    device_class: temperature
    state_class: measurement
    unit_of_measurement: "°C"

ota:
  - platform: esphome
    password: !secret ota_pwd

wifi:
  #  use_address: ${ip_address}
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret ota_pwd

## Captive portal when wifi connection fails
captive_portal:
